### ISSUE TITLE
Paginated Table collapses actions selection with different browser sizes

### ISSUE THREAD

**Issue by dbhaasis** [teamsnap/teamsnap-ui#312]
There are several sizing spacing issue with paginated table that occur when on different browser window sizes. The bulk actions will collapse when pagination buttons take a lot of space along with using the search function. 

The pagination buttons also seem to take up a lot of space and may want to make the controls a bit smaller.

**Comment by bradcypert** [comment]
We recently added changes too the pagination table to help it feel more responsive. This includes collapsing into a stack of full width components on the actions, search, and pagination buttons.

Additionally, the pagination buttons were given a scrollable overflow (maybe not the best solution) so that they would still function regardless of screen size.

Are there more changes that come to mind?
